changelog:
  exclude:
    labels:
      - "cicd"
    authors:
      - dependabot
  categories:
    - title: "⚠️ Breaking changes"
      labels:
        - "breaking"
    - title: "🚀 New features"
      labels:
        - "enhancement"
    - title: "📖 Documentation"
      labels:
        - "documentation"
    - title: "🐛 Bug fixes"
      labels:
        - "bug"
    - title: Other Changes
      labels:
        - "*"
